### ISSUE TITLE
Add viewpager indicator for photogallery

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#33]
dots at the bottom that indicate more images available

**Comment by dbykovsky** [comment]
Note for myself: try this solution 
https://github.com/ipereziriarte/image-pager-indicator OR
http://androidopentutorials.com/android-image-slideshow-using-viewpager/

**Comment by dbykovsky** [comment]
Done https://github.com/dbykovsky/sumofusM/commit/5175fdcbbf2fc2897e66eb646a893e092d7f6593
