### ISSUE TITLE
Set toolbar color as a palete on Campaign Detail

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#35]
get the main color from the main image and use that color.

**Comment by dbykovsky** [comment]
I researched this option and it looks like I will need to clarify with Nathan or Eric how to do that. Toolbar is not a palette. I need to figure out how to set vibrant into toolbar.

**Comment by alberto-campos** [comment]
Yes, this is a rough one. I had a hard time with it, too.

**Comment by dbykovsky** [comment]
Won't fix. Dunno how.
