### ISSUE TITLE
Fix toolbar on Sign in petition. It's white now

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#37]

**Comment by AndreSand** [comment]
@alberto-campos @dbykovsky 

Fixed in latest push.

**Comment by AndreSand** [comment]
@alberto-campos @dbykovsky 

We can close this issue, it's fixed now.

**Comment by AndreSand** [comment]
Done. 

Fix in https://github.com/dbykovsky/sumofusM/pull/62

@alberto-campos @dbykovsky

Please close issue.

**Comment by alberto-campos** [comment]
Fixed. Thanks Andres.
