### ISSUE TITLE
Fix progress bar percentage white color

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#39]
Bring text to the front

**Comment by dbykovsky** [comment]
I spent some time investigating, but i wasn't able to fix it. Progress bar is a custom implementation of TextView and somehow setText() won't bring text on top of the Drawable which is progress itself.  I'll address this question to Nathan.

**Comment by dbykovsky** [comment]
Done https://github.com/dbykovsky/sumofusM/issues/42
