### ISSUE TITLE
Add decimal point to the goal 

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#40]
Mask the goal amount to numeric

**Comment by alberto-campos** [comment]
Done.
Sample output:
a)
-- Goal: 500000  --> Goal: 500.0 k signatures
b) 
-- Goal 910  --> Goal: 910 signatures

**Comment by dbykovsky** [comment]
From my understanding (making notes), Eric asked us to use a decimal points which is: 
Goal of 500000 = 500,000
Goal of 56000 = 56,000
Goal of 1000 = 1,000

Please see another example http://action.sumofus.org/a/eu-ban-sulfoxaflor/?sub=homepage

**Comment by alberto-campos** [comment]
Fixed.
Also, Eric mentioned that it was confusing to know what that number represented. Most of the time he thought this was a dollar amount. I added 'signatures' at the end of the amount.
