### ISSUE TITLE
Add Shared Element Activity Transition from List of Camps to Camp Detail Activity

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#42]

**Comment by dbykovsky** [comment]
Phase 1 https://github.com/dbykovsky/sumofusM/commit/6fc6f68cbd3b907b2bb56368c2ceba6aef3ff0f1

**Comment by dbykovsky** [comment]
Phase2 https://github.com/dbykovsky/sumofusM/commit/4d9d11c7d900de88c6d21c1ddd98cd2b0ef92485

Added "Take action" button to the transition

**Comment by dbykovsky** [comment]
Done https://github.com/dbykovsky/sumofusM/issues/42
