### ISSUE TITLE
Sign "Message" needs to display all text

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#48]
Currently, the message to support a campaign is hidden if we have more than 3 lines of text in a relatively small phone. i.e. Nexus 5.

We need to change the height to fit text.

**Comment by dbykovsky** [comment]
I can take this one

**Comment by dbykovsky** [comment]
Done. Merged https://github.com/dbykovsky/sumofusM/commit/4d9d11c7d900de88c6d21c1ddd98cd2b0ef92485
