### ISSUE TITLE
Adding Campaigns tab on Drawer

### ISSUE THREAD

**Issue by AndreSand** [dbykovsky/sumofusM#53]
Adding Campaigns tab on Drawer

**Comment by dbykovsky** [comment]
Why do ween campaigns on  the drawer? Can you please attach screenshot to
see how it's going to look like?

**Comment by AndreSand** [comment]
@dbykovsky @alberto-campos What do you guys think?

<img width="487" alt="screen shot 2015-10-30 at 2 00 08 pm" src="https://cloud.githubusercontent.com/assets/8283868/10857995/d4fbc5e0-7f0e-11e5-95d0-119a02ae4f4e.png">

**Comment by AndreSand** [comment]
We need to change the image on the left of Campaigns :+1: :+1:

**Comment by dbykovsky** [comment]
This looks nice. Why do we need campaigns there?

**Comment by AndreSand** [comment]
I was thinking it will be good UX :)
@dbykovsky

**Comment by dbykovsky** [comment]
Let's leave the structure as is.
1. Drawer looks nice, but please take out "campaigns" menu item for now.
2. Is our new color Green? Please make Drawer background of the color of
   the app.
3. Fix all bugs for user profile page. It doesn't look nice (see
   screenshot  attached).
   - There is no default picture but button CAMERA button
   - If you take pic/select existing, picture is not set into image view.
     You need to leave Profile page and come back again to see profile pic
   - Why is sumofus logo on the right from the Add Credit Card button?
   - Make user be able to update phone number. It's not being saved on
     parse for now
   - make user image round

If you make your next pull request with all listed above, bu without extra
code that is not related to those items, that would be nice.

**Comment by AndreSand** [comment]
@dbykovsky Latest push fixes above issues :+1:  :smiley:

**Comment by AndreSand** [comment]
closing will not implement this

**Comment by AndreSand** [comment]
closing will not implement this
