### ISSUE TITLE
Update picture once user selected/taken picture 

### ISSUE THREAD

**Issue by AndreSand** [dbykovsky/sumofusM#61]
Update picture once user selected/taken picture

**Comment by AndreSand** [comment]
Done. 

Fix in https://github.com/dbykovsky/sumofusM/pull/62

**Comment by alberto-campos** [comment]
@dbykovskyy-trulia  This is the one you fixed now, correct?

**Comment by dbykovsky** [comment]
Yep, should be fixed. Let me know if there are bugs. I still need to cover one thing – to lower down user image in the Navigation Drawer
