### ISSUE TITLE
Make default user profile picture consistent

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#75]
1) In Menu - we show a large circle. Inside that there is a smaller circle on top of a half circle.
2) Click on Profile, user will be taken to the profile view. The default image is a colored image or the picture the user selected.

**Comment by alberto-campos** [comment]
@AndreSand can you take a look at this?

**Comment by dbykovsky** [comment]
@alberto-campos since changes were made to User profile and Navigation Drawer do we still need to make changes specified in this issue? If yes what are those?

**Comment by alberto-campos** [comment]
Nice, this is looking great!! It's consistent now. 
But we can still make a few improvements.
In the Menu:
1) Bring the image down, currently it's partially with the Toolbar.
2) There is a lot of empty space
In the Profile view
1) There is a thick line dividing the toolbar and the view.
2) Maybe look at other App examples and try to make it look similar.

**Comment by dbykovsky** [comment]
1)i just pushed fix for this
2) Let's discuss that tomorrow if we can fill that with something

1) I'll remove that thick line
2)Sure. Let's do this as a part of 2) above?

**Comment by alberto-campos** [comment]
Denys,

I thought you fixed the Menu - Profile image. When an user uploads a picture I thought we were showing their picture and not the placeholder?

**Comment by dbykovsky** [comment]
looking into

**Comment by alberto-campos** [comment]
oh, you have to close the app or logout and then log back in to see it.

**Comment by dbykovsky** [comment]
It's not good. I have 2 days old build on my phone, and it's working. Must
be some changes last two days. I'm fixing merge conflicts, then commit a
new video implementation and I'll take a look at profile

**Comment by alberto-campos** [comment]
Fixed. Verified.
