### ISSUE TITLE
Persist profile picture

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#76]
Once the user selects or takes a picture, we should save it in Parse.
@AndreSand Andres, can you take a look at this?

**Comment by dbykovsky** [comment]
@alberto-campos @AndreSand I'm fixing this now sine Andres hasn't responded yet.

**Comment by dbykovsky** [comment]
Done https://github.com/dbykovsky/sumofusM/commit/f6672666b06b7833116ce143e010f4a057018751

**Comment by AndreSand** [comment]
@alberto-campos @dbykovsky I believed I did this already.

What is the bug? Thanks.

**Comment by dbykovsky** [comment]
Bug was related to using Date stamp in file name. Parse rejected date in file name or date format was incorrect.
