### ISSUE TITLE
Theme Color - Vote.

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#84]
Suggestions 

By Alberto - 
Blue an Orange

<pre><code>
        color name="primary">#4285f4
        color name="primary_dark">#002663
        color name="primary_light">#BBDEFB
        color name="accent">#f4b400
        color name="primary_text">#212121
        color name="secondary_text">#727272
        color name="campaign_main_text">#F0FFFF
        color name="campaign_secondary_text">#FFFAFA
        color name="icons">#FFFFFF
        color name="divider">#B6B6B6

</code></pre>

By Denys @dbykovskyy-trulia 

By Andres @AndreSand

**Comment by dbykovsky** [comment]
I'm note sure how to vote for that. What color represents what? 

Let's take baby steps:
Lets change these three colors first and see how app is looking. Let's narrow down vote options to three colors for now including floating button color. 

//top nav bar colors
Current color for .colorPrimary = <color name="colorPrimary">#673AB7</color>
Current color for colorPrimaryDark = <color name="colorPrimaryDark">#512DA8</color>
//this is floating button
Current color for colorAccent=  <color name="colorAccent">#FF4081</color>

ALBERTO.colorPrimary = <color name="colorPrimary">#4285f4</color>
ALBERTO.colorPrimaryDark = <color name="colorPrimaryDark">#002663</color>
ALBERTO.colorAccent=  <color name="colorAccent">#f4b400</color>

This is color mapping for colors above http://developer.android.com/training/material/images/ThemeColors.png

**Comment by AndreSand** [comment]
Lets use the colors from sumofus.org teal, white, orange?
http://sumofus.org/

colorPrimary = #0199AD
colorPrimaryDark = #015D6D
colorAccent= #FF594B

FYI: On Android Studio, cmd+shift+a , search "color picker"

Thanks.

**Comment by dbykovsky** [comment]
Let's pick the final color scheme tomorrow before the class. It should be 3 lines change to change main colors of the app?

**Comment by alberto-campos** [comment]
1)  colors.xml

resources
      color name="window_background">#0199AD
...
color name="colorPrimary">#0199AD
color name="colorPrimaryDark">#015D6D
color name="colorAccent">#FF594B

AND
2) styles.xml
style name="Base.Theme.DesignDemo" parent="Theme.AppCompat.Light.NoActionBar"
    item name="colorPrimary">#0199AD
    item name="colorPrimaryDark">#015D6D
    item name="colorAccent">#FF594B
    item name="android:windowBackground">@color/window_background

**Comment by alberto-campos** [comment]
Will use sum of us colors.
