### ISSUE TITLE
Campaign Detail View - add arrow to "Take Action" when user finishes reading campaign

### ISSUE THREAD

**Issue by alberto-campos** [dbykovsky/sumofusM#86]
Or give some indication that there is no more content and user should Sign the Petition.

**Comment by dbykovsky** [comment]
Alberto, can you please clarify this flow in steps.

**Comment by alberto-campos** [comment]
At the end of a campaign description in Sum of Us they show the Copyright, Year, and Social media icons.

For us, we could show something to indicate that there is no more text to read. And perhaps take advantage of the fact that the user finished reading to animate the "Take Action" button.

**Comment by alberto-campos** [comment]
Done.
When user has already signed this campaign, we show a Green Checked box.
